name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: user/pc_inventory:latest

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yaml up -d

      - name: Run Tests
        run: docker-compose run --rm web sh -c "python manage.py test"
        env:
          POSTGRES_DB: pc_inventory
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

  deploy:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: javier1520docker/pc_inventory:latest

      - name: echo success
        run: echo 'Successfully executed'
