name: Build and Deploy

on:
  # workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run : pipenv install --dev

      - name: Run tests
        run: pipenv run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - name: echo success
        run: echo 'Successfully executed'